// 72631e54-78a4-11d0-bcf7-00aa00b7b32a
// typedef struct {     
//  UINT32 Data1;
//  UINT16 Data2;
//  UINT16 Data3;
//  UINT8  Data4[8]; 
// } EFI_GUID;
byte = {ASCII_HEX_DIGIT{2,2}}
part1_u32 = {ASCII_HEX_DIGIT{8,8}}
part2_u16 = {ASCII_HEX_DIGIT{4,4}}
part3_u16 = {ASCII_HEX_DIGIT{4,4}}
part4_u8_8 = {byte{2,2} ~ "-" ~ byte{6,6}}
guid = { part1_u32 ~ "-" ~ part2_u16 ~ "-" ~ part3_u16 ~ "-" ~ part4_u8_8 }